# name: Build & Deploy Spring app

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-deploy:
#     name: Build and Deploy Spring boot for beginner
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install JDK 17 Amazon Corretto
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget
#           wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
#           tar xvf amazon-corretto-17-x64-linux-jdk.tar.gz
#           export JAVA_HOME=$PWD/amazon-corretto-17.0.0.35.2-linux-x64/
#           export PATH=$JAVA_HOME/bin:$PATH

#       - name: Unit Tests
#         run: mvn -B test --file pom.xml

#       - name: Build the application
#         run: |
#           mvn clean
#           mvn -B package --file pom.xml
          
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Build Docker Image
#         run: |
#           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 150685619118.dkr.ecr.us-east-1.amazonaws.com
#           docker build -t 150685619118.dkr.ecr.us-east-1.amazonaws.com/spring-boot:latest .

#       - name: Push to ECR
#         run: |
#           docker push 150685619118.dkr.ecr.us-east-1.amazonaws.com/spring-boot:latest



name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:latest
